---
- name: load secrets
  include_vars: "install_openvpn_secrets.yml"
  no_log: true
- name: copy openvpn config
  copy:
    src: "src/etc/openvpn/{{ item }}"
    dest: "/etc/openvpn/{{ item }}"
  with_items:
    - server.conf
    - server-tcp.conf    
    - ca.crt
    - server.crt
    - server.key
    - dh1024.pem
- name: set ip forwarding in proc and the sysctl conf file and reload
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    # sysctl_set: yes
    reload: yes    
- name: enable and restart openvpn services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - openvpn@server
    - openvpn@server-tcp
